go:
    cgo: true
    version: 1.13
repository:
    path: github.com/spagno/iscdhcpd_exporter
build:
    flags: -a -tags netgo
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20180826-05:18:05"}}
tarball:
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - linux/arm
        - linux/arm64
        - linux/mips
        - linux/mipsle
        - linux/mips64
        - linux/mips64le
        - linux/ppc64
        - linux/ppc64le
        - linux/s390x
